### ISSUE TITLE
Make plugin browser independent and more stable

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/floorplan-generator#1]
Clear COBie (and other -ie) dependency, make it more server-side stable and browser independent (now only works on firefox)

**Comment by OhmSweetOhm** [comment]
Current version works with all browsers if it is running on a Web server.  I use a Chrome plugin that sets up a local Webserver then view the output from the local web server.

The COBie dependencies are a bit more troublesome.  One of the driving forces behind the whole project is COBie and how we may efficiently view COBie within the architectural context. However, as things go forward I would expect refactoring to slowly unwind some of these dependencies.
